classdef SimulatedLightcrafter505 < symphonyui.core.descriptions.RigDescription
    
    methods
        
        function obj = SimulatedLightcrafter505()
            import symphonyui.builtin.daqs.*;
            import symphonyui.builtin.devices.*;
            import symphonyui.core.*;
            
            daq = HekaSimulationDaqController();
            obj.daqController = daq;
            
            % Rig name and laboratory.
            rigDev = manookinlab.devices.RigPropertyDevice('RiekeLab','SimulatedLightcrafter');
            obj.addDevice(rigDev);
            
            amp1 = MultiClampDevice('Amp1', 1).bindStream(daq.getStream('ao0')).bindStream(daq.getStream('ai0'));
            obj.addDevice(amp1);

            % Add an analog trigger device to simulate the MEA.
            trigger = UnitConvertingDevice('ExternalTrigger', 'V').bindStream(daq.getStream('ao1'));
            obj.addDevice(trigger);
           
            % The 505 nm LED.
            greenRamp = importdata(edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'green_led_gamma_ramp.txt'));
            green = CalibratedDevice('Green LED', Measurement.NORMALIZED, greenRamp(:, 1), greenRamp(:, 2)).bindStream(daq.getStream('ao2'));
            
            green_ndfs = {'C1', 'C2', 'C3', 'C4', 'C5'};
            green.addConfigurationSetting('ndfs', {}, ...
                'type', PropertyType('cellstr', 'row', green_ndfs));
            
            greenAttenuations = containers.Map( ...
                {'C1', 'C2', 'C3', 'C4', 'C5'}, ...
                {0.2866, 0.5933, 0.9675, 1.9279, 2.1372});
            
            green.addResource('ndfAttenuations', greenAttenuations);
            
            green.addConfigurationSetting('gain', '', ...
                'type', PropertyType('char', 'row', {'', 'low', 'medium', 'high'}));
            
            greenFluxFactorPaths = containers.Map( ...
                {'low', 'medium', 'high'}, { ...
                edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'green_led_low_flux_factors.txt'), ...
                edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'green_led_medium_flux_factors.txt'), ...
                edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'green_led_high_flux_factors.txt')});
            green.addResource('fluxFactorPaths', greenFluxFactorPaths);
            
            greenFluxFactorTable = containers.Map( ...
                {'low', 'medium', 'high'}, { ...
                readtable(greenFluxFactorPaths('low')),...
                readtable(greenFluxFactorPaths('medium')),...
                readtable(greenFluxFactorPaths('high'))});
            
            greenFluxFactors = containers.Map( ...
                {'low', 'medium', 'high'}, {...
                greenFluxFactorTable('low').factor(greenFluxFactorTable('low').date == max(greenFluxFactorTable('low').date)),...
                greenFluxFactorTable('medium').factor(greenFluxFactorTable('medium').date == max(greenFluxFactorTable('medium').date)),...
                greenFluxFactorTable('high').factor(greenFluxFactorTable('high').date == max(greenFluxFactorTable('high').date))});
                
            
            green.addConfigurationSetting('lightPath', 'below', 'isReadOnly', true);
            green.addResource('spectrum', importdata(edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'green_led_spectrum.txt')));
            obj.addDevice(green);
            
            
%              trigger1 = UnitConvertingDevice('Trigger1', symphonyui.core.Measurement.UNITLESS).bindStream(daq.getStream('doport1'));
%             daq.getStream('doport1').setBitPosition(trigger1, 0);
%             obj.addDevice(trigger1);
%             
%             trigger2 = UnitConvertingDevice('Trigger2', symphonyui.core.Measurement.UNITLESS).bindStream(daq.getStream('doport1'));
%             daq.getStream('doport1').setBitPosition(trigger2, 2);
%             obj.addDevice(trigger2);
            
            % Add frame Monitor device
            frameMonitor = UnitConvertingDevice('Frame Monitor', 'V').bindStream(obj.daqController.getStream('ai7'));
            obj.addDevice(frameMonitor);
            
            % Add microns per pixel
            microdisplay = edu.washington.riekelab.rezeanu.devices.SimulatedLcrVideoMode('micronsPerPixel', 3.07);
            
            %Add flux factor paths
            fluxFactorPaths = containers.Map( ...
                {'auto', 'red', 'green', 'blue'}, { ...
                edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_auto505_flux_factors.txt'), ...
                edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_red505_flux_factors.txt'), ...
                edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_green505_flux_factors.txt'), ...
                edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_blue505_flux_factors.txt')});
            
            microdisplay.addResource('fluxFactorPaths', fluxFactorPaths);
            
            % Load the flux factor table
            fluxFactorTable = containers.Map( ...
                {'red', 'green', 'blue', 'auto'}, { ...
                readtable(fluxFactorPaths('red')), ...
                readtable(fluxFactorPaths('green')), ...
                readtable(fluxFactorPaths('blue')), ...
                readtable(fluxFactorPaths('auto'))...
                });
            
            % Pull most recent flux factors
            fluxFactors = containers.Map( ...
                {'red', 'green', 'blue', 'auto'}, { ...
                fluxFactorTable('red').factor(fluxFactorTable('red').date == max(fluxFactorTable('red').date)),...
                fluxFactorTable('green').factor(fluxFactorTable('green').date == max(fluxFactorTable('green').date)),...
                fluxFactorTable('blue').factor(fluxFactorTable('blue').date == max(fluxFactorTable('blue').date)),...
                fluxFactorTable('auto').factor(fluxFactorTable('auto').date == max(fluxFactorTable('auto').date))});
            
            % Add light path
            lightPath = 'below';
            microdisplay.addConfigurationSetting('lightPath', lightPath, 'isReadOnly', true);
            
            % Add spectra
            lcr_spectrum = containers.Map( ...
                {'auto', 'red', 'green', 'blue'}, { ...
                    importdata(edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_auto505_spectrum.txt')), ...
                    importdata(edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_red505_spectrum.txt')), ...
                    importdata(edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_green505_spectrum.txt')), ...
                    importdata(edu.washington.riekelab.Package.getCalibrationResource('rigs', 'suction', 'lightcrafter_below_blue505_spectrum.txt'))...
                    }...
                );
            
            microdisplay.addResource('spectrum', lcr_spectrum);
            
            ndfs = {'FW00', 'FW05', 'FW20', 'FW30', 'FW40', 'C1', 'C2', 'C3', 'C4', 'C5'};

            % Add NDF names
            microdisplay.addConfigurationSetting('ndfs', {}, ...
                'type', PropertyType('cellstr', 'row', ndfs));
            
            % Add NDF attenuations
            attenuations = containers.Map( ...
                {'auto','red', 'green', 'blue'}, { ...
                containers.Map( ...
                    {'FW00', 'FW05', 'FW10', 'FW20', 'FW30', 'FW40','C1', 'C2', 'C3', 'C4', 'C5'}, ...
                    {0, 0.5153, 1.0175, 2.1873, 3.2603, 4.3110, 0.2866, 0.5460, 0.9675, 1.9279, 2.1372}), ...
                containers.Map( ...
                    {'FW00', 'FW05', 'FW10', 'FW20', 'FW30', 'FW40','C1', 'C2', 'C3', 'C4', 'C5'}, ...
                    {0, 0.5089, 1.0047, 2.0381, 3.0604, 4.0434, 0.2866, 0.5945, 0.9675, 1.9279, 2.1372}), ...
                containers.Map( ...
                    {'FW00', 'FW05', 'FW10', 'FW20', 'FW30', 'FW40','C1', 'C2', 'C3', 'C4', 'C5'}, ...
                    {0, 0.5074, 1.0031, 2.1752, 3.2626, 4.2867, 0.2866, 0.5470, 0.9675, 1.9279, 2.1372}), ...
                containers.Map( ...
                    {'FW00', 'FW05', 'FW10', 'FW20', 'FW30', 'FW40','C1', 'C2', 'C3', 'C4', 'C5'}, ...
                    {0, 0.5312, 1.0494, 2.4151, 3.6192, 4.7103, 0.2663, 0.5140, 0.9569, 2.0810, 2.3747})});
                
            microdisplay.addResource('ndfAttenuations', attenuations);    
                
            % Compute quantal catch (species, spectrum, attenuations,
            % fluxFaactors, current ndfs, light path, pr_orientation
            species = edu.washington.riekelab.sources.primate.Primate();
            qCatch = edu.washington.riekelab.rezeanu.utils.getQuantalCatch(...
                species, lcr_spectrum, attenuations, fluxFactors, {}, lightPath, 'down');
                       
            microdisplay.addResource('quantalCatch', qCatch);
            
            % Binding the video device to an unused stream only so its configuration settings are written to each epoch.
            microdisplay.bindStream(daq.getStream('doport1'));
            daq.getStream('doport1').setBitPosition(microdisplay, 15);    
            obj.addDevice(microdisplay);
            
            % Add mea device (this will fail, but it more accurately
            % represents what figures will be shown on screen)
            mea = manookinlab.devices.MEADevice(9001);
            obj.addDevice(mea);
            
            % Add the filter wheel.
%             filterWheel = manookinlab.devices.FilterWheelDevice('comPort', 'COM13');
%             obj.addDevice(filterWheel);
        end
    end
    
end

